# https://taskfile.dev

version: '3'

tasks:
  generate-llvm:
    cmds:
      - clang -S -emit-llvm {{ .CLI_ARGS }}.c -o {{ .CLI_ARGS }}.ll
    desc: Generate LLVM IR from C source file
  compile-llvm:
    cmds:
      - clang {{ .CLI_ARGS }}.ll -c -o {{ .CLI_ARGS }}.o
      - clang {{ .CLI_ARGS }}.o $(find . -wholename './dist/lib/*.o') -o {{ .CLI_ARGS }}
      - ./{{ .CLI_ARGS }}
    desc: Compile LLVM IR to executable
  compile-c:
    cmds:
      - clang {{ .CLI_ARGS }}.c -o {{ .CLI_ARGS }}
      - ./{{ .CLI_ARGS }}
    desc: Compile C source file to executable
